// <auto-generated />
namespace Sprint33.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ref2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ref2));
        
        string IMigrationMetadata.Id
        {
            get { return "202006300908336_ref2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
